server:
  port: 9002
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.37.79.57:3306/shop?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
  jap:
    database: MySQL
    show-sql: true
    open-in-view: true

eureka:
  instance:
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

logging:
  level:
    com.demo.order.feign.ProductFeignClient: debug
feign:
  client:
   config:
     product-service:
       loggerLevel: FULL
  #开启对hystrix的支持(feign已经集成了hystrix，开启即可)
  hystrix:
    enabled: true

#为dashboard暴露接口
management:
  endpoints:
    web:
      exposure:
        include: '*'

#修改ribbon负载均衡策略 （默认轮询）  服务名-ribbon- NFLoadBalancerRualClassName:策略
#order-service:
#  ribbon:
   # NFLoadBalancerRualClassName: com.netflix.loadbalancer.RandomRule

#    ConnectTimeout: 250 #ribbon的链接超时时间
#    ReadTimeout: 1000 #ribbon的数据读取超时时间
#    OkToRetryOnAllOperations: true #是否对所有操作进行重试
#    MaxAutoRetriesNextServer: 1 #切换实例重试次数
#    MaxAutoRetries: 1 #对当前实例重试次数